version: '2'
services:
  vimbadmin:
    image: bytecast/vimbadmin
    ports:
      - '80:80'
    environment:
      - MYSQL_PASSWORD=XXX
      - ADMIN_EMAIL=info@domain.com
      - ADMIN_PASSWORD=XXX2
      - SALT_MAILBOX=REPLACE_WITH_64_CHAR_RANDOM_STRING
      - SALT_SECURITY=REPLACE_WITH_ANOTHER_64_CHAR_RANDOM_STRING
    volumes:
      - ./config/:/tmp/docker-vimbadmin/
    links:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: XXX3
